Moving wrapper script args
opensciencegrid/virtual-school-2021 pull request #31
Opened 2021-07-30 20:39 UTC by ChristinaLK

Making the wrapper script args section required, and rewriting to use with the blast example instead of OpenBUGS

2021-07-30 20:45 UTC, ChristinaLK commented
completely untested. 😂

2021-08-03 02:42 UTC, lmichael107 requested changes

2021-08-03 02:42 UTC, lmichael107 commented on docs/materials/software/part1-ex3-arguments.md
> +Software Exercise 4.1: Passing Arguments Through the Wrapper Script
```suggestion
Software Exercise 1.3: Passing Arguments Through the Wrapper Script
```

2021-08-03 02:45 UTC, lmichael107 reviewed
Exercises 4.2-4.4 corrected to 4.1-4.3, but they're internal titles still need to be updated. Will merge (so this can all be tested) and then make the changes in a new pull request.

2021-08-03 02:45 UTC, lmichael107 commented on docs/materials/index.md
>  - [Exercise 4.2: Additional Python ](software/part4-ex2-python-extras.md)
```suggestion
- [Exercise 4.1: Additional Python ](software/part4-ex2-python-extras.md)
```

2021-08-03 02:45 UTC, lmichael107 commented on docs/materials/index.md
>  - [Exercise 4.3: Using Software in a Docker Container](software/part4-ex3-docker.md)
```suggestion
- [Exercise 4.2: Using Software in a Docker Container](software/part4-ex3-docker.md)
```

2021-08-03 02:45 UTC, lmichael107 commented on docs/materials/index.md
>  - [Exercise 4.4: Building Your Own Docker Container (Beta)](software/part4-ex4-docker-build.md)
```suggestion
- [Exercise 4.3: Building Your Own Docker Container (Beta)](software/part4-ex4-docker-build.md)
```

2021-08-03 02:46 UTC, lmichael107 approved these changes

2021-08-03 02:46 UTC, merged